spring:
  oauth2:
    client:
      kakao:
        grant_type: ${KAKAO_OAUTH_GRANT_TYPE}
        client_id: ${KAKAO_OAUTH_CLIENT_ID}
        redirect_uri: ${KAKAO_OAUTH_REDIRECT_URI}
      naver:
        grant_type: ${NAVER_OAUTH_GRANT_TYPE}
        client_id: ${NAVER_OAUTH_CLIENT_ID}
        client_secret: ${NAVER_OAUTH_CLIENT_SECRET}
        state: ${NAVER_OAUTH_STATE}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
