spring:
  profiles:
    group:
      local: domain, infrastructure
      dev: domain, infrastructure
    active: local
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB