name: CD - Deploy to Production Server

on:
  push:
    branches: [ "dev" ]  # dev 브랜치에 푸시 시 실행

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: meerket-bucket
  CODE_DEPLOY_APPLICATION_NAME: meerket-dev
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: meerket-deployment-group

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2) JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      # 3) .env 파일 생성
      - name: Create .env file from Secret
        run: |
          echo "${{ secrets.ENV_PROD }}" | base64 --decode > ./meerket/.env

      # 4) Firebase JSON 키 생성
      - name: Create Firebase JSON Key
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "meerket-83e38-firebase-adminsdk-gyt9i-d2df62fdf4.json"
          json: ${{ secrets.FIREBASE_SERVICE_KEY }}
          dir: './meerket/meerket-application/src/main/resources'

      # 5) gradlew 실행 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./meerket/gradlew

      # 6) Gradle 빌드
      - name: Build with Gradle
        working-directory: ./meerket
        run: |
          ./gradlew clean build -x test --no-daemon --info
          if [ -f ./meerket-application/build/libs/meerket-application-0.0.1.jar ]; then
            echo "JAR file generated successfully!"
          else
            echo "JAR file not found! Please check the build configuration."
            exit 1
          fi

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: [ build ] # build 작업 완료 후 실행

    steps:
      # 1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2) AWS 인증 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      # 3) S3에 프로젝트 업로드
      - name: Upload to AWS S3
        run: |
          cd meerket
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --source .
          echo "S3 Upload completed. Verifying contents in S3..."
          aws s3 ls s3://meerket-bucket/

      # 4) EC2에 배포
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
