name: CD - Deploy to Production Server

on:
  push:
    branches: [ "main" ]  # main 브랜치 푸시 시 실행

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃 -> 최신 코드를 Github Actions환경으로 가져온다.
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build Application
        run: ./gradlew clean build --no-daemon --info

      # 4. SSH Key 설정
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_EC2_SSH_KEY }}" > ~/.ssh/prod_key
          chmod 600 ~/.ssh/prod_key

      # 5. 파일 전송 및 배포
      - name: Deploy to Production Server
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/prod_key \
            build/libs/*.jar \
            ${{ secrets.PROD_EC2_USER }}@${{ secrets.PROD_EC2_HOST }}:/home/ubuntu/app-prod.jar

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prod_key ${{ secrets.PROD_EC2_USER }}@${{ secrets.PROD_EC2_HOST }} << 'EOF'
            cd /home/ubuntu
            pkill -f app-prod.jar || true  # 기존 프로세스 종료
            nohup java -jar app-prod.jar > prod-output.log 2>&1 &
          EOF
